### ISSUE TITLE
GTX 1060 Benchmark Results

### ISSUE THREAD

**Issue by mwareslicer** [lachesis/scallion#102]
Hi,

I have an Asus Strix Gtx 1060 6Gb OC and this are my benchmark results:

Nr. | LoopIteration | HashCount | Speed | Runtime | Predicted | Search String
-|----------------|--------------|--------|-----------|------------|---------------
1 | 10479 | 175808,45MH | 3382,2MH/s | 00:00:51 | 00:02:42 | prefixab
2 | 6790 | 113917,30MH | 3419,4MH/s | 00:00:33 | 00:02:40 | T5P4wLCO
3 | 45383 | 761400,39MH | 3474,3MH/s | 00:03:39 | 00:02:38 | wCpiFflm
4 | 48151 | 807839,73MH | 3503,0MH/s | 00:03:50 | 00:02:36 | vku7Ip4g
5 | 32819 | 550611,45MH | 3484,5MH/s | 00:02:38 | 00:02:37 | CUzoFCny

My Gpu is overclocked and air cooled at 2114 Mhz.

I hope I cloud help you with this.

**Comment by 734MNOOB** [comment]
Some really good results. I have a http://www.geforce.com/hardware/desktop-gpus/geforce-gtx-960 that I am testing this weekend along with a live linux instance running on a 2012 Macbook Pro.

**Comment by LucasRoot** [comment]
I have a GTX 1060 6GB from gigabyte, I'm going to test it too, but not overclocked.

**Comment by LucasRoot** [comment]
I'm getting around 2200 MH/s

**Comment by lachesis** [comment]
Thanks - if you want to add these to the README, feel free to make a pull request.
