### ISSUE TITLE
GTX 1080 Ti Benchmark Results

### ISSUE THREAD

**Issue by Oros42** [lachesis/scallion#120]
To help you for the README.  
  
GPU : GTX 1080 Ti at 1873 Mhz  
CPU : AMD FX-8320E Eight-Core Processor × 8  
OS : Linux Mint 18.2 Sonya 64-bit  
  
| Nr.      | Loop Iteration | HashCount    | Speed      | Runtime  | Predicted | Search String |
| -------- | ------------- | ------------ | ---------- | -------- | --------- | ------------- |
|  1 best  | 6132          | 102877,89MH  | 8472,9MH/s | 00:00:12 | 00:01:04  | prefixab      |
|  1 worst | 42750         | 717225,98MH  | 8573,9MH/s | 00:01:23 | 00:01:04  | prefixab      |
|  2 best  | 5348          | 89724,55MH   | 8433,6MH/s | 00:00:10 | 00:01:05  | T5P4wLCO      |
|  2 worst | 138190        | 2318443,48MH | 8327,1MH/s | 00:04:38 | 00:01:06  | T5P4wLCO      |
|  3 best  | 92891         | 1558452,37MH | 8333,0MH/s | 00:03:07 | 00:01:05  | wCpiFflm      |
|  3 worst | 101977        | 1710890,16MH | 8331,9MH/s | 00:03:25 | 00:01:05  | wCpiFflm      |
|  4 best  | 7100          | 119118,23MH  | 8432,0MH/s | 00:00:14 | 00:01:05  | vku7Ip4g      |
|  4 worst | 45702         | 766752,33MH  | 8354,4MH/s | 00:01:31 | 00:01:05  | vku7Ip4g      |
|  5 best  | 4169          | 69944,21MH   | 8449,4MH/s | 00:00:08 | 00:01:05  | CUzoFCny      |
|  5 worst | 56506         | 948013,37MH  | 8173,7MH/s | 00:01:55 | 00:01:07  | CUzoFCny      |

**Comment by freethenation** [comment]
Closing as this info is several years old and GPUs have come a long way since then
