### ISSUE TITLE
Request | how to use multiple GPUs ?

### ISSUE THREAD

**Issue by kolet** [lachesis/scallion#121]
hi, for instance i have 2-4 gpus, 
how can i use them all at ones  to Generate an address ?

-d 2 3 4 wont work
neither -d 1  -d 2 -d 3 

it will select only 1 gpu at the time.

**Comment by aeryncaen** [comment]
Run multiple processes. The work is probabilistic, so running multiple instances won't duplicate effort, it'll reduce the time it takes for an address to generate. Only downside is that they won't all auto-top when an address is generated, so you'll have to check on it periodically.

**Comment by freethenation** [comment]
Yep, this is covered in the README under `How can you use multiple devices?`
