### ISSUE TITLE
Has anyone got it working on Ubuntu 18.04 yet?

### ISSUE THREAD

**Issue by nthall350** [lachesis/scallion#127]
I just spent a few hours trying to get it running. I finally managed to get it built, but when I ran it nothing happened. I got another shell prompt like I had just hit enter with no command every time I tried. No errors.

I tried rebooting the PC one last time but it crashed when x windows was loading. I'm assuming it's a video driver issue. I had to leave for work, so that's as far as I got. I'm using a GTX 970, with the Nvdia 390 drivers.

**Comment by freethenation** [comment]
I had no issues getting it working but you are not alone. I know this issue is old but if you are having issues you can try the dockerized version I just accepted a pull request for.
