### ISSUE TITLE
Add an option to generate url not just with custom prefix, but for example with regex, or other generation rules

### ISSUE THREAD

**Issue by SoptikHa2** [lachesis/scallion#139]
Maybe I don't want URL to start with exclusively `myapp`, maybe I'm okay with `m14pp`, or even `.{2}app`. It would be nice to allow regexes, so we can describe to requested prefix by this, so we could get one of the desired urls much faster.

**Comment by freethenation** [comment]
It is in the readme? https://github.com/lachesis/scallion#multipattern-hashing

Regexs are compiled to a lookup table so not all regex features can be implemented. You can read/extend the current regex implementation: https://github.com/lachesis/scallion/blob/gpg/scallion/RegexPattern.cs .
