### ISSUE TITLE
Option to change algorithm?

### ISSUE THREAD

**Issue by CashCode** [lachesis/scallion#145]
Option to change from RSA to ECDSA?
I want to use scallion to generate pgp vanity fingerprint, but I can't change the algorithm and I can't input a passphrase.
In output it gives only private key and hash, without public key, how to import it in pgp? Gives error that public key is empty.
Any solution?

**Comment by lachesis** [comment]
No, sorry. We're fairly tightly wedded to how RSA works in our fast work generation for the GPU. It is possible to do for ECDSA but would be a lot of work. If you can code, you could start with oclvanitygen from bitcoin. About 7 years old now but IIRC it has working ECDSA key enumeration on the GPU.
