### ISSUE TITLE
Generate adresse with 012 89

### ISSUE THREAD

**Issue by Wirloo** [lachesis/scallion#153]
Hi why we can generate a domain with 0-1-2-8-9 on eshalot but not in scallion?

**Comment by lachesis** [comment]
From the README:
```
What are valid characters?

Tor .onion addresses use Base32, consisting of all letters and the digits 2 through 7, inclusive. They are case-insensitive.
```
Perhaps `eshalot` (tho I cannot find that software anywhere) uses the new form of Tor hidden service addresses which are completely different and cannot be efficiently solved using Scallion's approach (although other GPU-based approaches may exist, I don't have time to investigate them these days).

**Comment by Wirloo** [comment]
https://github.com/ReclaimYourPrivacy/eschalot

They do that since 2013

But they just use cpu, so its too long ^^
