### ISSUE TITLE
Error: docker run --runtime= nvidia-ti --rm scallion -l

### ISSUE THREAD

**Issue by dimingchan** [lachesis/scallion#171]
When I run the command "docker run --runtime= nvidia-ti --rm scallion -l", I get an error. I ask ChatGPT to execute docker login scallion first, how do I solve this problem?

[root@centos-s-2vcpu-4gb-nyc1-01 src]# docker run --runtime=nvidia -ti --rm scallion -l
Unable to find image 'scallion:latest' locally
docker: Error response from daemon: pull access denied for scallion, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.

**Comment by we1rdw4y** [comment]
Sup, actual problem is - your docker instance doesnt have image named `scallion`, and cannot find it on dockerhub.
U can check available locally images by running `docker images`
In case there are no scallion images - u need to pull with proper name or build images yourself

**Comment by lachesis** [comment]
You will want to build the docker image locally with something like:
```docker build -t scallion:latest .```

**Comment by lachesis** [comment]
The steps are documented in the readme here:

https://github.com/lachesis/scallion?tab=readme-ov-file#docker-linux-nvidia-gpus-only

Also please note that Tor has fully deprecated v2 Onion addresses so you won't be able to generate working Onion addresses with this tool.
