### ISSUE TITLE
Option to use multiple devices

### ISSUE THREAD

**Issue by zerodrama** [lachesis/scallion#23]
Is there a way to code it to allow use of multiple devices?

**Comment by lachesis** [comment]
Yep, that's what the "-d" switch is for. If you do "-l" it will show all
your devices. "--help" can tell you more.

I don't know anything about newer card performance, but I've seen estimates
ranging anywhere from 600MH/s to 1GH/s for newer card. As you'll see, it
doesn't really matter.

For now, let's assume 1GH/s for each card. The Titans will likely be well
below this (Nvidia hardware has poor integer performance), but whatever.

That's 21 \* 1GH/s or 21 GH/s. The formula for calculating the ETA is

seconds = 2^(5*length-1) / hashspeed

So, 2 ^ (5*16 - 1) / (21 \* 10^9) = 28783948086062 seconds = ~900,000 years.

A 12-character hash would be more tenable, at only around 11 months on
average.
