### ISSUE TITLE
Scallion hangs after Looks good

### ISSUE THREAD

**Issue by bartbroere** [lachesis/scallion#39]
I have set up an ubuntu machine with all requirements. I built scallion from source and I downloaded the binary. When testing the setup however, it hangs after Looks good. Adding the -n also didn't work. It doesn't respond to anything, even Ctrl^C doesn't work.

ubuntu@ubuntu:~/scallion/scallion/bin/Debug$ mono scallion.exe -n test
Cooking up some delicions scallions...
Using kernel normal from file kernel.cl (Normal)
Using work group size 32
Compiling kernel... done.
Testing SHA1 hash...
CPU SHA-1: d3486ae9136e7856bc42212385ea797094475802
GPU SHA-1: d3486ae9136e7856bc42212385ea797094475802
Looks good!

My apologies if this is a known issue. I have tried googling for a solution.

**Comment by neuman1812** [comment]
Is there any update on this?  My scallion locks up after a few moments..

$ mono scallion.exe -d 0 onionirc
Cooking up some delicions scallions...
Using kernel optimized from file kernel.cl (Optimized4)
Using work group size 32
Compiling kernel... done.
Testing SHA1 hash...
CPU SHA-1: d3486ae9136e7856bc42212385ea797094475802
GPU SHA-1: d3486ae9136e7856bc42212385ea797094475802
Looks good!
LoopIteration:137  HashCount:2298.48MH  Speed:468.4MH/s  Runtime:00:00:04  Predicted:00:19:33  

From there it just hangs.

**Comment by DarkCenobyte** [comment]
I make it work today, using also ami-87377cee. I think your problem came from the mono version from Ubuntu repositories. It is incompatible with scallion (it hangs/crash/...), you must use the last stable with:
> sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
> echo "deb http://download.mono-project.com/repo/debian wheezy main" | sudo tee /etc/apt/sources.list.d/mono-xamarin.list
> apt-get update

then if you already had mono installed:

> apt-get upgrade

else install it with:

> apt-get install mono-complete

**Comment by lachesis** [comment]
Awesome, thanks for the workaround. I'm going to close this for now, as this issue is fixed with newer mono.
