### ISSUE TITLE
Needed >18 hours instead of 7 hours. Bug?

### ISSUE THREAD

**Issue by JHGitty** [lachesis/scallion#49]
CPU: Intel Core i7-3770k.
GPU: nVidia EVGA GTX 680 Classified

I bruteforced a 9 character long prefix.
It should take around 7 hours. It really needed 18 hours and 51 minutes.

Why so long? Bug?
---
init: 464ms / 1 (464ms, 2,16/s)
generate key: 1540738ms / 44969 (34,26ms, 29,19/s)
cpu precompute: 1740ms / 44969 (0,04ms, 25844,25/s)
total without init: 67914829ms / 1 (67914829ms, 0/s)
set buffers: 18121ms / 2787744 (0,01ms, -83175,5/s)
write buffers: 78186ms / 2787744 (0,03ms, -19277,41/s)
read results: 67257445ms / 2787744 (24,13ms, -22,41/s)
check results: 6585ms / 2787744 (0ms, -228887,36/s)
688,67 million hashes per second
---
LoopIteration:2787732  HashCount:46770381,91MH  Speed:688,7MH/s  Runtime:18:51:5
LoopIteration:2787733  HashCount:46770398,69MH  Speed:688,7MH/s  Runtime:18:51:5
LoopIteration:2787734  HashCount:46770415,47MH  Speed:688,7MH/s  Runtime:18:51:5
LoopIteration:2787735  HashCount:46770432,25MH  Speed:688,7MH/s  Runtime:18:51:5
LoopIteration:2787736  HashCount:46770449,02MH  Speed:688,7MH/s  Runtime:18:51:5
LoopIteration:2787737  HashCount:46770465,80MH  Speed:688,7MH/s  Runtime:18:51:5
LoopIteration:2787738  HashCount:46770482,58MH  Speed:688,7MH/s  Runtime:18:51:5
LoopIteration:2787739  HashCount:46770499,35MH  Speed:688,7MH/s  Runtime:18:51:5
LoopIteration:2787740  HashCount:46770516,13MH  Speed:688,7MH/s  Runtime:18:51:5
LoopIteration:2787741  HashCount:46770532,91MH  Speed:688,7MH/s  Runtime:18:51:5
LoopIteration:2787742  HashCount:46770549,69MH  Speed:688,7MH/s  Runtime:18:51:5
LoopIteration:2787743  HashCount:46770566,46MH  Speed:688,7MH/s  Runtime:18:51:5
LoopIteration:2787744  HashCount:46770583,24MH  Speed:688,7MH/s  Runtime:18:51:5
4  Predicted:07:05:45  Found new key! Found 1 unique keys.

Calculation
---
2^(5*(9 characters)-1)/(688000000 Hashes per second)/(60 seconds)/(60 minutes)
~ 7,1 hours

**Comment by lachesis** [comment]
No, searching for hashes is a probabilistic process, just like Bitcoin
mining. There's no upper or lower bound on the number of tries (and
therefore time) required to solve a particular pattern. Variances 2 or
3x are uncommon but not surprising for a small number of patterns.

However, if you've solved, say, 100 8-character prefixes and on average
they take 2-3x the predicted time, something might be up. We've not done
a lot of testing with nvidia cards, although they clearly are able to
produce results.

On 01/18/2015 06:21 PM, JHGitty wrote:
>
> CPU: Intel Core i7-3770k.
> GPU: nVidia EVGA GTX 680 Classified
>
> I bruteforced a 9 character long prefix.
> It should take around 7 hours. It really needed 18 hours and 51 minutes.
>
> ------------------------------------------------------------------------
>
> init: 464ms / 1 (464ms, 2,16/s)
> generate key: 1540738ms / 44969 (34,26ms, 29,19/s)
> cpu precompute: 1740ms / 44969 (0,04ms, 25844,25/s)
> total without init: 67914829ms / 1 (67914829ms, 0/s)
> set buffers: 18121ms / 2787744 (0,01ms, -83175,5/s)
> write buffers: 78186ms / 2787744 (0,03ms, -19277,41/s)
> read results: 67257445ms / 2787744 (24,13ms, -22,41/s)
> check results: 6585ms / 2787744 (0ms, -228887,36/s)
>
>
>     688,67 million hashes per second
>
> LoopIteration:2787732 HashCount:46770381,91MH Speed:688,7MH/s
> Runtime:18:51:5
> LoopIteration:2787733 HashCount:46770398,69MH Speed:688,7MH/s
> Runtime:18:51:5
> LoopIteration:2787734 HashCount:46770415,47MH Speed:688,7MH/s
> Runtime:18:51:5
> LoopIteration:2787735 HashCount:46770432,25MH Speed:688,7MH/s
> Runtime:18:51:5
> LoopIteration:2787736 HashCount:46770449,02MH Speed:688,7MH/s
> Runtime:18:51:5
> LoopIteration:2787737 HashCount:46770465,80MH Speed:688,7MH/s
> Runtime:18:51:5
> LoopIteration:2787738 HashCount:46770482,58MH Speed:688,7MH/s
> Runtime:18:51:5
> LoopIteration:2787739 HashCount:46770499,35MH Speed:688,7MH/s
> Runtime:18:51:5
> LoopIteration:2787740 HashCount:46770516,13MH Speed:688,7MH/s
> Runtime:18:51:5
> LoopIteration:2787741 HashCount:46770532,91MH Speed:688,7MH/s
> Runtime:18:51:5
> LoopIteration:2787742 HashCount:46770549,69MH Speed:688,7MH/s
> Runtime:18:51:5
> LoopIteration:2787743 HashCount:46770566,46MH Speed:688,7MH/s
> Runtime:18:51:5
> LoopIteration:2787744 HashCount:46770583,24MH Speed:688,7MH/s
> Runtime:18:51:5
>
>
>     4 Predicted:07:05:45 Found new key! Found 1 unique keys.
>
> Bug?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lachesis/scallion/issues/49>.
>

-- 
Eric Swanson
http://www.alloscomp.com/
