### ISSUE TITLE
The passed regex string is not valid!

### ISSUE THREAD

**Issue by JHGitty** [lachesis/scallion#50]
I use the binary linked in the documentation here on GitHub.

I run the command "scallion.exe test123". The error occures if I add any number. The command "scallion.exe test" works. I use Windows 8.1 x64.

Error
---
```
Cooking up some delicions scallions...

Unbehandelte Ausnahme: System.ArgumentException: The passed regex string is not
valid!
   bei scallion.RegexPattern.SingleRegexPattern..ctor(String regex, Int32 output Length, String validCharacters) in C:\Users\FreeTop\projects\scallion\scallion\RegexPattern.cs:Zeile 76.
   bei scallion.RegexPattern.<>c__DisplayClass2.<.ctor>b__0(String i) in C:\Users\FreeTop\projects\scallion\scallion\RegexPattern.cs:Zeile 16.
   bei System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   bei System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   bei System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   bei scallion.RegexPattern..ctor(String regex, Int32 outputLength, String validCharacters) in C:\Users\FreeTop\projects\scallion\scallion\RegexPattern.cs:Zeile 15.
   bei scallion.OnionToolConfig.CreateRegexPattern(String pattern) in C:\Users\F
reeTop\projects\scallion\scallion\OnionToolConfig.cs:Zeile 27.
   bei scallion.ToolConfig..ctor(String pattern) in C:\Users\FreeTop\projects\sc
allion\scallion\ToolConfig.cs:Zeile 30.
   bei scallion.OnionToolConfig..ctor(String pattern) in C:\Users\FreeTop\projec
ts\scallion\scallion\OnionToolConfig.cs:Zeile 10.
   bei scallion.CLRuntime.Run(ProgramParameters parms) in C:\Users\FreeTop\proje
cts\scallion\scallion\CLRuntime.cs:Zeile 252.
   bei scallion.Program.Main(String[] args) in C:\Users\FreeTop\projects\scallio
n\scallion\Program.cs:Zeile 433.

Stopping the GPU and shutting down...

```

**Comment by lachesis** [comment]
Base32 only supports the characters A-Z and the numbers 2-7 (all
inclusive). You'll notice that 26 letters + 6 numbers = 32 possible
characters. So if you use the numbers 0, 1, 8, or 9, you'll get that error.

You can find some documentation on base 32 in the relevant RFC:
https://www.ietf.org/rfc/rfc3548.txt. Search for "Table 3: The Base 32
Alphabet".

On 01/18/2015 06:25 PM, JHGitty wrote:
>
> I use the binary linked in the documentation here on GitHub.
>
> I run the command "scallion.exe test123". The error occures if I add
> any number.
> I use Windows 8.1 x64.
>
>
>     Error
>
> Cooking up some delicions scallions...
>
> Unbehandelte Ausnahme: System.ArgumentException: The passed regex
> string is not
> valid!
> bei scallion.RegexPattern.SingleRegexPattern..ctor(String regex, Int32
> output
> Length, String validCharacters) in
> C:\Users\FreeTop\projects\scallion\scallion\R
> egexPattern.cs:Zeile 76.
> bei scallion.RegexPattern.<>c__DisplayClass2.<.ctor>b__0(String i) in
> C:\User
> s\FreeTop\projects\scallion\scallion\RegexPattern.cs:Zeile 16.
> bei System.Linq.Enumerable.WhereSelectArrayIterator|2.MoveNext()
> bei System.Linq.Buffer|1..ctor(IEnumerable|1 source)
> bei System.Linq.Enumerable.ToArray[TSource](IEnumerable|1 source)
> bei scallion.RegexPattern..ctor(String regex, Int32 outputLength,
> String vali
> dCharacters) in
> C:\Users\FreeTop\projects\scallion\scallion\RegexPattern.cs:Zeil
> e 15.
> bei scallion.OnionToolConfig.CreateRegexPattern(String pattern) in
> C:\Users\F
> reeTop\projects\scallion\scallion\OnionToolConfig.cs:Zeile 27.
> bei scallion.ToolConfig..ctor(String pattern) in
> C:\Users\FreeTop\projects\sc
> allion\scallion\ToolConfig.cs:Zeile 30.
> bei scallion.OnionToolConfig..ctor(String pattern) in
> C:\Users\FreeTop\projec
> ts\scallion\scallion\OnionToolConfig.cs:Zeile 10.
> bei scallion.CLRuntime.Run(ProgramParameters parms) in
> C:\Users\FreeTop\proje
> cts\scallion\scallion\CLRuntime.cs:Zeile 252.
> bei scallion.Program.Main(String[] args) in
> C:\Users\FreeTop\projects\scallio
> n\scallion\Program.cs:Zeile 433.
>
> Stopping the GPU and shutting down...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lachesis/scallion/issues/50>.
>

-- 
Eric Swanson
http://www.alloscomp.com/

**Comment by JHGitty** [comment]
I think it would be better to catch this exception and output your answer instead of this error.

**Comment by s72785** [comment]
this is a git patched are welcome ;)

**Comment by lachesis** [comment]
Yep, as @s72785 said, we're happy to take pull requests. Make sure you
verify that the issue is the presence of an illegal character and not a
malformed regexp.
On 01/19/2015 06:20 AM, s72785 wrote:
>
> this is a git patched are welcome ;)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lachesis/scallion/issues/50#issuecomment-70498754>.
>

-- 
Eric Swanson
http://www.alloscomp.com/
