### ISSUE TITLE
Problems with prediction time.

### ISSUE THREAD

**Issue by agustinx19** [lachesis/scallion#52]
A) When I try to find a lot of prefixes the prediction time is so big that ends in an error, not allowing me find large amounts of prefixes, is there any way to disable the prediction of time?

![aaa](https://cloud.githubusercontent.com/assets/10744797/5942983/df2e8a22-a6f9-11e4-9c91-2bb57c129a6f.jpg)

B) Is not possible take longer to find  test[234567]test that test4test

![2](https://cloud.githubusercontent.com/assets/10744797/5942909/97674a4e-a6f9-11e4-9809-5b18eb5edccc.jpg)

**Comment by zero10** [comment]
The problem looks to be this line in OnionToolConfig.cs.  Line 15:
var hashes_per_win = _regex.GenerateAllPatternsForRegex().Select(t=>Math.Pow(2,5*t.Count(q=>q!='.') - 1)).Sum();

I don't think it should end in a Sum().  Having more possibilities should increase the chances of finding a solution, no?  Also it is mentioned in the readme that regex matching for multiple solutions is not typically much slower than a single solution.

**Comment by richardklafter** [comment]
@zero10 I would agree that looks like an issue. `test1` should take about twice as long as `test[12]`. @zero10 If you want to take a shot at fixing it I will review. If not I will take a look at it when I am back in the US.

**Comment by zero10** [comment]
@richardklafter I was reviewing this further and now feel my issue is separate from the one raised by @agustinx19 in this issue.  I will open a new one for the bug I would like addressed.

**Comment by freethenation** [comment]
Pull request #66 was merged the issue should be fixed if you build from source.
