### ISSUE TITLE
Initial Crash when trying to generate over 12 character words

### ISSUE THREAD

**Issue by ticoombs** [lachesis/scallion#56]
Using Windows Binary. Version 2.0

Command to replicate bug:
```
scallion.exe -c "thisis13charZ" -o test.txt
```

```
Unhandled Exception: System.OverflowException: TimeSpan overflowed because the d
uration is too long.
   at System.TimeSpan.Interval(Double value, Int32 scale)
   at System.TimeSpan.FromSeconds(Double value)
   at scallion.OnionToolConfig.PredictRuntime(Int64 hashRate) in C:\Users\FreeTo
p\projects\scallion\scallion\OnionToolConfig.cs:line 17
   at scallion.CLRuntime.Run(ProgramParameters parms) in C:\Users\FreeTop\projec
ts\scallion\scallion\CLRuntime.cs:line 441
   at scallion.Program.Main(String[] args) in C:\Users\FreeTop\projects\scallion
\scallion\Program.cs:line 433

Stopping the GPU and shutting down...
```

**Comment by lachesis** [comment]
What's your hashrate? It looks to me like it's going to take more than
2^32 seconds to calculate, which is tooooo long! :)

On 04/15/2015 03:31 PM, Tim Coombs wrote:
>
> Using Windows Binary. Version 2.0
>
> Command to replicate bug:
>
> |scallion.exe -c "thisis13charZ" -o test.txt
> |
> |Unhandled Exception: System.OverflowException: TimeSpan overflowed because the d
> uration is too long.
>    at System.TimeSpan.Interval(Double value, Int32 scale)
>    at System.TimeSpan.FromSeconds(Double value)
>    at scallion.OnionToolConfig.PredictRuntime(Int64 hashRate) in C:\Users\FreeTo
> p\projects\scallion\scallion\OnionToolConfig.cs:line 17
>    at scallion.CLRuntime.Run(ProgramParameters parms) in C:\Users\FreeTop\projec
> ts\scallion\scallion\CLRuntime.cs:line 441
>    at scallion.Program.Main(String[] args) in C:\Users\FreeTop\projects\scallion
> \scallion\Program.cs:line 433
>
> Stopping the GPU and shutting down...
> |
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lachesis/scallion/issues/56>.
>

-- 
Eric Swanson
http://www.alloscomp.com/

**Comment by ticoombs** [comment]
2222MH/s

I'm happy to wait a week or two. 
But this also happens when using regex as well. 
"thirteen.letter" also results in the same crash. 


On 16 April 2015 1:29:36 PM AEST, Eric Swanson <notifications@github.com> wrote:
>What's your hashrate? It looks to me like it's going to take more than
>2^32 seconds to calculate, which is tooooo long! :)
>
>On 04/15/2015 03:31 PM, Tim Coombs wrote:
>>
>> Using Windows Binary. Version 2.0
>>
>> Command to replicate bug:
>>
>> |scallion.exe -c "thisis13charZ" -o test.txt
>> |
>> |Unhandled Exception: System.OverflowException: TimeSpan overflowed
>because the d
>> uration is too long.
>>    at System.TimeSpan.Interval(Double value, Int32 scale)
>>    at System.TimeSpan.FromSeconds(Double value)
>>    at scallion.OnionToolConfig.PredictRuntime(Int64 hashRate) in
>C:\Users\FreeTo
>> p\projects\scallion\scallion\OnionToolConfig.cs:line 17
>>    at scallion.CLRuntime.Run(ProgramParameters parms) in
>C:\Users\FreeTop\projec
>> ts\scallion\scallion\CLRuntime.cs:line 441
>>    at scallion.Program.Main(String[] args) in
>C:\Users\FreeTop\projects\scallion
>> \scallion\Program.cs:line 433
>>
>> Stopping the GPU and shutting down...
>> |
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/lachesis/scallion/issues/56>.
>>
>
>-- 
>Eric Swanson
>http://www.alloscomp.com/
>
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/lachesis/scallion/issues/56#issuecomment-93628588

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by shancat** [comment]
FYI using the calculations in the README and based off your stated rate of 2222MH/s the predicted time is over 260 years not a week or two. The number of seconds would need 33 bytes to store which is why it overflows the 32 bytes
