### ISSUE TITLE
System.DllNotFoundException at start

### ISSUE THREAD

**Issue by globus243** [lachesis/scallion#58]
When I start Scallion this is what I get
````
C:\Users\Administrator\Desktop\scallion-v2.0>scallion.exe Test

Unhandled Exception: System.TypeInitializationException: The type initializer fo
r 'OpenSSL.Core.Native' threw an exception. ---> System.DllNotFoundException: Un
able to load DLL 'libeay32': The specified module could not be found. (Exception
 from HRESULT: 0x8007007E)
   at OpenSSL.Core.Native.ERR_load_crypto_strings()
   at OpenSSL.Core.Native..cctor() in C:\Users\FreeTop\projects\scallion\openssl
-net-0.5\ManagedOpenSsl\Core\Native.cs:line 172
   --- End of inner exception stack trace ---
   at OpenSSL.Core.Native.InitializeThreads()
   at OpenSSL.Core.ThreadInitialization.InitializeThreads() in C:\Users\FreeTop\
projects\scallion\openssl-net-0.5\ManagedOpenSsl\Core\Native.cs:line 103
   at scallion.Program.Main(String[] args) in C:\Users\FreeTop\projects\scallion
\scallion\Program.cs:line 306
````

Short info: trying this on a amazon EC2 G.large Instance with windows server 2012 (because on ubuntu bumblebee didn'T work). I Installed MS c++ 2008 Redistributable and OpenSSL from this page http://slproweb.com/products/Win32OpenSSL.html

**Comment by globus243** [comment]
The above mentioned issue happened on an Windows Server 2012 Basic.
I testet it on a completly naked and freshly imaged windows Server 2008 with ONLY vcredist_x86 and Win32OpenSSL-1_0_2a installed

**Comment by richardklafter** [comment]
What binary are you using? Did ya build it? Its a dependency issue... we include the correct binaries for OpenSSL at https://github.com/lachesis/scallion/blob/gpg/openssl-net-0.5/native/windows/x86/libeay32.dll and https://github.com/lachesis/scallion/blob/gpg/openssl-net-0.5/native/windows/x86/ssleay32.dll so you should not need to install them. 

Make sure those dlls are in the same folder as scallion.exe. Also, ya may run into issues if using RDP: https://github.com/lachesis/scallion/issues/38 (although I have not tested this in sometime)

**Comment by globus243** [comment]
I used the Binary you provided under https://github.com/lachesis/scallion#binary-download
For Windows Server I would bet it's that RDP error, seems pretty conclusively... I guess I need to try it on linux machines again.

**Comment by TheSkorm** [comment]
This is still a bug.

This is as far as I got for working out how to do it. After installing Cuda drivers the box failed to restart though. For running on Amazon you need to
1. Install CUDA drivers from nvidia - https://developer.nvidia.com/cuda-downloads
1. Install your own OpenSSL libs
1. Delete libeay32.dll and ssleay32.dll from the scallion dir

**Comment by My1** [comment]
I also have the problem. althouhg I even "unlocked" the files (windows likes to block files which are from the internet)
running win8.1

**Comment by ofek** [comment]
Install [https://www.microsoft.com/en-us/download/details.aspx?id=8328](https://www.microsoft.com/en-us/download/details.aspx?id=8328)

**Comment by pk910** [comment]
thank you ofek, that fixed it for me.
this schould be added to the Dependencies section of the README...

**Comment by techsoulman** [comment]
That link you offered is dead now ofek, would you mind updating it? I'm really stuck on this one.

**Comment by ofek** [comment]
@techsoulman Fixed.

**Comment by techsoulman** [comment]
Thank you for that ofek. Unfortunately, it didn't help with my problem. 

I am getting the same message as globus243 on my Windows 10 Desktop PC.
