### ISSUE TITLE
Unable to choose which GPU to use with Scallion

### ISSUE THREAD

**Issue by MattJacob1981** [lachesis/scallion#59]
I have a decent ATI graphics card and one of the newer Intel chips (which have integrated graphics). When I run Scallion it runs off the CPU and I want it to run off the GPU. I'm not sure how to configure Scallion for this? I used the pre-built distribution...

**Comment by freethenation** [comment]
It is a command line program type scallion -h and read through the options. If you are still having trouble post the full command your running.

**Comment by MattJacob1981** [comment]
Thanks, yah I did not realize I could select the device in the command line...
