### ISSUE TITLE
System.ArgumentException: Illegal character in base32 encoded string

### ISSUE THREAD

**Issue by J-kit** [lachesis/scallion#63]
Hey, the generator doesn't work with specific parameters:
\scallion-v0.9>scallion.exe 1000
Cooking up some delicions scallions...
Using kernel optimized4_9 from file kernel.cl (Optimized4_9)

Unbehandelte Ausnahme: System.ArgumentException: Illegal character in base32 encoded string
   bei scallion.TorBase32.FromBase32Str(String str)
   bei scallion.CLRuntime.Run(Int32 deviceId, Int32 workGroupSize, Int32 workSize, Int32 numThreadsCreateWork, KernelType kernelt, Int32 keysize, String prefix, String suffix)
Please Fix this!
Thank you!

**Comment by lachesis** [comment]
Your input is invalid. Tor onion URLs support the characters a-z and the
numbers 2-7.

On 10/02/2015 02:18 PM, J-kit wrote:
>
> Hey, the generator doesn't work with specific parameters:
> \scallion-v0.9>scallion.exe 1000
> Cooking up some delicions scallions...
> Using kernel optimized4_9 from file kernel.cl (Optimized4_9)
>
> Unbehandelte Ausnahme: System.ArgumentException: Illegal character in
> base32 encoded string
> bei scallion.TorBase32.FromBase32Str(String str)
> bei scallion.CLRuntime.Run(Int32 deviceId, Int32 workGroupSize, Int32
> workSize, Int32 numThreadsCreateWork, KernelType kernelt, Int32
> keysize, String prefix, String suffix)
> Please Fix this!
> Thank you!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lachesis/scallion/issues/63>.
>

-- 
Eric Swanson
http://www.alloscomp.com/
