### ISSUE TITLE
VC++ Redistributable 2008 required on Windows - documentation update suggested and fix for crash with incorrect error message.

### ISSUE THREAD

**Issue by engren** [lachesis/scallion#64]
The documentation should include information and links to the relevant Visual C++ redistributable files required to run this on Windows - be it WIndows 7, 8, 8.1 or 10.

I just worked my way down from VC++ Redistributable 2015 down to 2008 before managing to get it running - it was failing on libeay32.dll, saying "not found", which was found to be incorrect after some in depth binary debugging.

The correct error message should have been that the necessary VC++ files were missing. Maybe that can be arranged at the same time as updating the documentation?

**Comment by richardklafter** [comment]
I have been maintaining scallion's windows support with an old windows gaming laptop running windows 7 (linux is my primary OS these days). Just to confirm `VC++ Redistributable 2008` (https://www.microsoft.com/en-us/download/details.aspx?id=5582) was the version that ended up working for you?

**Comment by engren** [comment]
That is correct, that was the one that finally made Scallion run on a fresh Windows 10 install.

**Comment by freethenation** [comment]
thanks for the info. readme has been updated
