### ISSUE TITLE
Prediction time scales incorrectly with multiple solution regexes

### ISSUE THREAD

**Issue by zero10** [lachesis/scallion#65]
If I run the program like this:
scallion.exe -d 0 "test2345"
On my hardware I get a predicted time of approximately 12 minutes, however if I run the program like this:
scallion.exe -d 0 "test234[56]"
it predicts approximately 24 minutes

The problem looks to be this line in OnionToolConfig.cs (Line 15):
var hashes_per_win = _regex.GenerateAllPatternsForRegex().Select(t=>Math.Pow(2,5*t.Count(q=>q!='.') - 1)).Sum();

I don't think it should end with a Sum().  Having more possible solutions seems like it should increase the chances of finding a solution and reduce the time. 

It is mentioned in the readme that regex matching for multiple solutions is not typically much slower than a single solution so I don't think it would be fair to essentially multiply the estimated time by the number of possible valid results.

**Comment by lachesis** [comment]
I guess we've since fixed this, because here is what I see:

```
$ mono scallion/bin/Debug/scallion.exe -d 0 "test2345" 
LoopIteration:264  HashCount:4429.19MH  Speed:2904.4MH/s  Runtime:00:00:01  Predicted:00:03:09

$ mono scallion/bin/Debug/scallion.exe -d 0 "test234[56]"
LoopIteration:262  HashCount:4395.63MH  Speed:2832.2MH/s  Runtime:00:00:01  Predicted:00:01:37
```

Thanks for the report!
