### ISSUE TITLE
Private key generation on different machine

### ISSUE THREAD

**Issue by LachlanGunn** [lachesis/scallion#68]
Hello,

Is there some way to perform private key generation on a different machine from the hashing?  Looking at the code it seems not, but I'm always happy to be surprised :)

My reason for doing so is that I'd like to be able to generate private keys locally and then do hashing on an Amazon S3 instance (it manages about 1.6GH/sec, so it shouldn't be too fast to permit pregeneration of the keys, and current spot pricing gives an average cost of about US$1.50 for a 9-character name).

If not, is this something that you'd be interested in incorporating if I had the time to write the code for it?

Thanks.
Lachlan

**Comment by lachesis** [comment]
The older branch, master, had some limited support for that. See
https://github.com/lachesis/scallion/tree/master#-secure-remote-key-generation.
If you wanted to port this code forward to the modern ("gpg") branch, I
would be happy to merge the PR. Alternatively, we'd also be interested
in a client-server model where the server generates keys on demand.

On 12/16/2015 06:49 AM, Lachlan Gunn wrote:
>
> Hello,
>
> Is there some way to perform private key generation on a different
> machine from the hashing? Looking at the code it seems not, but I'm
> always happy to be surprised :)
>
> My reason for doing so is that I'd like to be able to generate private
> keys locally and then do hashing on an Amazon S3 instance (it manages
> about 16GH/sec, so it shouldn't be too fast to permit pregeneration of
> the keys, and current spot pricing gives an average cost of about
> US$150 for a 9-character name)
>
> If not, is this something that you'd be interested in incorporating if
> I had the time to write the code for it?
>
> Thanks
> Lachlan
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lachesis/scallion/issues/68>.
>

-- 
Eric Swanson
http://www.alloscomp.com/

**Comment by LachlanGunn** [comment]
Thanks for your quick response.  Personally I'd prefer the client-server model, the less manual faffing about with keyfiles the better, and it means you can report results remotely, which would be really really useful when it's split over multiple instances.

**Comment by lachesis** [comment]
Agreed - that seems better, but isn't implemented right now. I'd love to take a PR for that, and I'm happy to review or collaborate if that would help you out, but I don't have time to do the full implementation right now.
