### ISSUE TITLE
V1.2 still ok to use?

### ISSUE THREAD

**Issue by danny91** [lachesis/scallion#71]
Hi i noticed V1.2 is the last version that supports secure third party generation. I'm wondering if its still ok to use this version? Or was their a major security update ext between it and the current? Thanks.

**Comment by lachesis** [comment]
There haven't been any significant security updates. It should still be
safe to use that version.

On 01/02/2016 04:11 AM, danny91 wrote:
>
> Hi i noticed V12 is the last version that supports secure third party
> generation I'm wondering if its still ok to use this version? Or was
> their a major security update ext between it and the current? Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lachesis/scallion/issues/71>.
>

-- 
Eric Swanson
http://www.alloscomp.com/
