### ISSUE TITLE
Fails to compile with mono 3.2.8.0 on Ubuntu 15.10

### ISSUE THREAD

**Issue by OSUI** [lachesis/scallion#72]
Terminal errors:

linux@linux:~/Scrivania/scallion-gpg$ sudo xbuild scallion.sln
XBuild Engine Version 12.0
Mono, Version 3.2.8.0
Copyright (C) 2005-2013 Various Mono authors

Build started 10/01/2016 17:06:35.

---

Project "/home/linux/(Desktop)/scallion-gpg/scallion.sln" (default target(s)):
    Target ValidateSolutionConfiguration:
: error : Error initializing task Message: Could not load file or assembly 'Microsoft.Build.Tasks.v4.0' or one of its dependencies. The system cannot find the file specified.
    Task "Message" execution -- FAILED
    Done building target "ValidateSolutionConfiguration" in project "/home/linux/(Desktop)/scallion-gpg/scallion.sln".-- FAILED
Done building project "/home/linux/(Desktop)/scallion-gpg/scallion.sln".-- FAILED

Build FAILED.
Errors:

/home/linux/(Desktop)/scallion-gpg/scallion.sln (default targets) ->
(ValidateSolutionConfiguration target) ->

```
: error : Error initializing task Message: Could not load file or assembly 'Microsoft.Build.Tasks.v4.0' or one of its dependencies. The system cannot find the file specified.

 0 Warning(s)
 1 Error(s)
```

Time Elapsed 00:00:01.1897210

**Comment by tommybananas** [comment]
Seeing the same failure on 14.04
XBuild Engine Version 12.0
Mono, Version 3.2.8.0

**Comment by freethenation** [comment]
Going to update instructions for building on 16.10... Closing this as obsolete
