### ISSUE TITLE
Errors Running Scallion

### ISSUE THREAD

**Issue by bkoffler** [lachesis/scallion#79]
I have been trying to get this program to work for some time and I continue to run into errors which are a bit beyond me. Any assistance on what i should be looking for would be greatly appeciated!

Stacktrace:

  at <unknown> <0xffffffff>
  at (wrapper managed-to-native) OpenTK.Compute.CL10.CL/Core.GetPlatformIDs (uint,intptr_,uint_) <0xffffffff>
  at OpenTK.Compute.CL10.CL.GetPlatformIDs (uint,intptr_,uint_) <0x0001b>
  at scallion.CLDeviceInfo.GetPlatformIds () <0x0001f>
  at scallion.CLDeviceInfo.GetDeviceIds () <0x0000b>
  at scallion.CLRuntime.GetDevices () <0x0000b>
  at scallion.Program.ListDevices () <0x0002b>
  at scallion.Program.Main (string[]) <0x00b2b>
  at (wrapper runtime-invoke) <Module>.runtime_invoke_void_object (object,intptr,intptr,intptr) <0xffffffff>

Native stacktrace:

```
/usr/bin/cli() [0x8105b4a]
/usr/bin/cli() [0x8153274]
/usr/bin/cli() [0x806a20b]
[0xb77bbc98]
/opt/AMDAPPSDK-3.0/lib/x86/libamdocl12cl32.so(+0x1695388) [0xb09bb388]
/opt/AMDAPPSDK-3.0/lib/x86/libamdocl12cl32.so(+0x572b8e) [0xaf898b8e]
/opt/AMDAPPSDK-3.0/lib/x86/libamdocl12cl32.so(+0x56fe71) [0xaf895e71]
/usr/lib/libamdocl32.so(aclCompile+0x178) [0xb269a9b8]
/usr/lib/libamdocl32.so(+0x320645) [0xb1c0c645]
/usr/lib/libamdocl32.so(+0x3450ea) [0xb1c310ea]
/usr/lib/libamdocl32.so(+0x2ec20d) [0xb1bd820d]
/usr/lib/libamdocl32.so(+0x2fd390) [0xb1be9390]
/usr/lib/libamdocl32.so(+0x2e8e5b) [0xb1bd4e5b]
/usr/lib/libamdocl32.so(+0x3298d9) [0xb1c158d9]
/usr/lib/libamdocl32.so(+0x32aada) [0xb1c16ada]
/usr/lib/libamdocl32.so(+0x32ac95) [0xb1c16c95]
/usr/lib/libamdocl32.so(+0x2e684f) [0xb1bd284f]
/usr/lib/libamdocl32.so(+0x302019) [0xb1bee019]
/usr/lib/libamdocl32.so(clIcdGetPlatformIDsKHR+0x85) [0xb1bbc695]
/opt/AMDAPPSDK-3.0/lib/x86/libOpenCL.so(+0x2006) [0xb72e2006]
/opt/AMDAPPSDK-3.0/lib/x86/libOpenCL.so(+0x5209) [0xb72e5209]
/lib/i386-linux-gnu/libpthread.so.0(__pthread_once+0x8e) [0xb773d36e]
/opt/AMDAPPSDK-3.0/lib/x86/libOpenCL.so(+0x52e7) [0xb72e52e7]
/opt/AMDAPPSDK-3.0/lib/x86/libOpenCL.so(+0x1f81) [0xb72e1f81]
/opt/AMDAPPSDK-3.0/lib/x86/libOpenCL.so(clGetPlatformIDs+0x23) [0xb72e2953]
[0xb5a966e0]
[0xb5a943a4]
[0xb5a942e0]
[0xb5a9420c]
[0xb5a9404c]
[0xb5a93d7c]
[0xb7370f0c]
[0xb737129e]
/usr/bin/cli() [0x8069bf0]
```

Debug info from gdb:

Could not attach to process.  If your uid matches the uid of the target
process, check the setting of /proc/sys/kernel/yama/ptrace_scope, or try
again as the root user.  For more details, see /etc/sysctl.d/10-ptrace.conf
ptrace: Operation not permitted.
No threads.
# 

Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
# used by your application.

Aborted (core dumped)

**Comment by lachesis** [comment]
Hmm, sorry I cannot help with this particular issue. See if you can get any of the OpenCL samples running on your machine first.
