### ISSUE TITLE
System.OverflowException on 14-character Onion pattern

### ISSUE THREAD

**Issue by Revertron** [lachesis/scallion#81]
D:\scallion-v2.0>scallion.exe -d 0 -c 14letterpattern[234567]
Cooking up some delicions scallions...
Using kernel optimized from file kernel.cl (Optimized4)
Using work group size 64
Compiling kernel... done.
Testing SHA1 hash...
CPU SHA-1: d3486ae9136e7856bc42212385ea797094475802
GPU SHA-1: d3486ae9136e7856bc42212385ea797094475802
Looks good!

Необработанное исключение: System.OverflowException: Переполнение TimeSpan из-за превышения длительности.
   в System.TimeSpan.Interval(Double value, Int32 scale)
   в System.TimeSpan.FromSeconds(Double value)
   в scallion.OnionToolConfig.PredictRuntime(Int64 hashRate) в C:\Users\FreeTop\projects\scallion\scallion\OnionToolConfig.cs:строка 17
   в scallion.CLRuntime.Run(ProgramParameters parms) в C:\Users\FreeTop\projects\scallion\scallion\CLRuntime.cs:строка 441
   в scallion.Program.Main(String[] args) в C:\Users\FreeTop\projects\scallion\scallion\Program.cs:строка 433

Stopping the GPU and shutting down...

Sorry, its in russian.

**Comment by lachesis** [comment]
You're attempting to find a hash matching far too complex of a pattern.
The exception warns that the number of seconds required to find it it is
greater than 2**32 (>136 years). You should try a shorter pattern.

On 05/22/2016 10:22 PM, Roman wrote:

> D:\scallion-v2.0>scallion.exe -d 0 -c somepattern[234567]
> Cooking up some delicions scallions...
> Using kernel optimized from file kernel.cl (Optimized4)
> Using work group size 64
> Compiling kernel... done.
> Testing SHA1 hash...
> CPU SHA-1: d3486ae9136e7856bc42212385ea797094475802
> GPU SHA-1: d3486ae9136e7856bc42212385ea797094475802
> Looks good!
> 
> Необработанное исключение: System.OverflowException: Переполнение
> TimeSpan из-за превышения длительности.
> в System.TimeSpan.Interval(Double value, Int32 scale)
> в System.TimeSpan.FromSeconds(Double value)
> в scallion.OnionToolConfig.PredictRuntime(Int64 hashRate) в
> C:\Users\FreeTop\projects\scallion\scallion\OnionToolConfig.cs:строка 17
> в scallion.CLRuntime.Run(ProgramParameters parms) в
> C:\Users\FreeTop\projects\scallion\scallion\CLRuntime.cs:строка 441
> в scallion.Program.Main(String[] args) в
> C:\Users\FreeTop\projects\scallion\scallion\Program.cs:строка 433
> 
> Stopping the GPU and shutting down...
> 
> Sorry, its in russian.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/lachesis/scallion/issues/81

## 

Eric Swanson
http://www.alloscomp.com/

**Comment by Revertron** [comment]
But the search is probabilistic. I may find that pattern on the first try. Isn't it?
P.S.: I have a decent video card, it gives me 1360MH/s.

**Comment by lachesis** [comment]
Sure, you "might" find it on the first try. However, the probability is extremely small, so small that it's not worth worrying about. You should just go buy lottery tickets - you're way more likely to win than to find that pattern in your lifetime. My computation suggests that you'll need to try (on average) 590295810358705651712 hashes to find a 14 character pattern. If you had 1000 of your video card running 24/7 at 1360MH/s, you'd find a hit (on average, meaning about 50% of the time) after 14 years.

Anyway, if you want to fix this bug, I'm happy to take your pull request.
