### ISSUE TITLE
not really an issue, but speed record, 4800MH/z!!!, also request to enforce full gpu clock

### ISSUE THREAD

**Issue by compsjp** [lachesis/scallion#83]
I have an EVGA 980 TI and OC, pulling 3000MH/z with help of enforcing higher gpu clocks

2930-3100 MH/z

**Comment by jtl999** [comment]
Neat.

I ordered a GTX 1070 for other reasons. Will benchmark with it when I receive it.

**Comment by compsjp** [comment]
ya know, this can be a request, have scallion enforce full gpu clock

run a game in background with just menus, not anything hogging gpu clock, but raising gpu clock.(turbo boost etc etc

run diablo 3 but stay in menus, overwatch, ark anything with simple menus but calls for gpu in game, will help with the mh/z

**Comment by jtl999** [comment]
Speed:4615.3MH/s

GTX 1070 headless under Ubuntu 16.04 with latest nVidia drivers. :D

**Comment by compsjp** [comment]
awesome dude(: wait till the nvidia 2000?

**Comment by jtl999** [comment]
yeah :D

**Comment by compsjp** [comment]
i did some overclocks, and its time to show off my 980 ti again.. 
LoopIteration:30303  HashCount:508399.98MH  Speed:4190.2MH/s  Runtime:00:02:01  Predicted:50953.17:03:02

after a while, i added a bit more overclock, come on baby, you can do it!
LoopIteration:694837  HashCount:11657430.43MH  Speed:4440.6MH/s  Runtime:00:43:45  Predicted:1538574.23:25:52

more overclocks added 30 more mhz core, 125 mhz more mem.
LoopIteration:766766  HashCount:12864198.80MH  Speed:4787.1MH/s  Runtime:00:44:47  Predicted:1427185.16:16:12

LoopIteration:1246922  HashCount:20919879.73MH  Speed:4800.3MH/s  Runtime:01:12:38  Predicted:1423266.01:29:18

http://www.compsman.com/scallionownage.jpg

update added more air flow

LoopIteration:79452  HashCount:1332983.37MH  Speed:4905.0MH/s  Runtime:00:04:31  Predicted:1392894.22:32:21

sorry jtl999 lol my 980 ti ftw evga still wins, :P

-g 64 seems the best on my 980 ti? i dunno hard to tell

**Comment by lachesis** [comment]
Nice, that is pretty fast! Were you able to find keys with that speed? If so, feel free to send a PR to add it to the README.

**Comment by jtl999** [comment]
I could probably try some overclocks of my own 😄 

My result was with no overclock whatsoever.
