### ISSUE TITLE
Oddity

### ISSUE THREAD

**Issue by Calver** [lachesis/scallion#88]
I'm using a AMD RX480 but getting a hashspeed of 22.1MH/s - I'm on windows. I'm obviously doing something wrong - any ideas?

**Comment by Calver** [comment]
and its not showing as a device either so I cant use the -h argument

**Comment by ChadTaljaardt** [comment]
do you have the latest drivers for everything?

Do you have any messages or errors?

**Comment by freethenation** [comment]
Closing this issue. Assuming it was a config issue.
