### ISSUE TITLE
scallion stops after ~210-~220 loopiterations

### ISSUE THREAD

**Issue by sebastianheyn** [lachesis/scallion#91]
Hi,

thanks for the code. 

I tried this on my gtx 560ti, (linux) however after some time the process stops. The program becomes unresponsive - ctrl+x etc dont work. I have to kill mono to stop the process.

Any idea?

**Comment by sebastianheyn** [comment]
strange. when restarting a couple of times it seems to work but not always

**Comment by freethenation** [comment]
Any luck reproducing? If not I am going to close the issue.
