### ISSUE TITLE
System.IO.FileNotFoundException

### ISSUE THREAD

**Issue by veteranxxx** [lachesis/scallion#97]
Hi, Windows server 2008, service pack 2, any ideas?

Unhandled Exception: System.IO.FileNotFoundException: Could not load file or ass
embly 'System.Core, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b77a5c56193
4e089' or one of its dependencies. The system cannot find the file specified.
File name: 'System.Core, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b77a5c
561934e089'
   at scallion.Program.Main(String[] args)

**Comment by veteranxxx** [comment]
i have downloaded net 3.5 fix, but scallion find error with ssleay32.dll and libeay32.dll, binary dll not worked for me. I have downloaded dll from here. 

github.com/paralect/robomongo/issues/786

then my scallion start like a gun machine :)

**Comment by lachesis** [comment]
Glad you solved it! I don't test or develop on Windows much anymore, so thanks for the info.
